#! /bin/sh

if [ ! -d /nobackup ] ; then
    return 0
fi

for i in
    /nobackup/$USER
    /auto/ws$USER-sjc
    /router
    /auto/xrut
    /usr/cisco
    /current
    /usr/atria
    /auto/iox
do
    _path -p $i
done

_cdpath /nobackup/$USER /nobackup /auto/ws$USER-sjc /tftpboot/$USER

export ACME_DIFF_OPTS='-u -b -B -p'

